### ISSUE TITLE
train_with_lm.py line 136. loss_token = (cls_token, gt_label_size)

### ISSUE THREAD

**Issue by wjhuang0113** [pooyafayyaz/Fingerspelling-PoseNet#2]
Hi,

I attempted to run your code, combining the training data of ChicagoFSWild and ChicagoFSWild+ for training. However, I encountered a bug while running train_with_lm.py.

On line 136 of train_with_lm.py: loss_token = (cls_token, gt_label_size) seems to be missing some code.

The error originates from line 138 of train_with_lm.py: loss = loss_dec + 5 * loss_enc + loss_token. 
Since loss_dec and loss_enc are tensors, but loss_token is a tuple, they cannot be added together.

Could you help fix this problem, Thanks!

**Comment by pooyafayyaz** [comment]
Thank you for your interest in our work. 
Could you update the line to:

`loss_token = loss_cls(cls_token, gt_label_size)`

It looks like the loss criterion is missing.

**Comment by wjhuang0113** [comment]
> Thank you for your interest in our work. Could you update the line to:
> 
> `loss_token = loss_cls(cls_token, gt_label_size)`
> 
> It looks like the loss criterion is missing.

Thank you for your reply. I will give it a try.

Additionally, I would like to ask how to use the failedhands.txt file generated by signing_hand_detection.py, such as how to apply it to the training code.

My idea is to remove the files listed in failedhands.txt from the training and test data, as this might result in better accuracy.

Could you help solve this problem, Thanks!

**Comment by atonyo11** [comment]
Hi @wjhuang0113,
I tried to run train_with_lm.py (did python extract_pose_mediapipe.py first for ChicagoFSWildPlus), but I encountered the error below. Did you experience anything similar?

`
device cuda
{0: '$', 1: "'", 2: ' ', 3: '&', 4: '.', 5: '@', 6: 'a', 7: 'c', 8: 'b', 9: 'e', 10: 'd', 11: 'g', 12: 'f', 13: 'i', 14: 'h', 15: 'k', 16: 'j', 17: 'm', 18: 'l', 19: 'o', 20: 'n', 21: 'q', 22: 'p', 23: 's', 24: 'r', 25: 'u', 26: 't', 27: 'w', 28: 'v', 29: 'y', 30: 'x', 31: 'z'}
{'$': 0, "'": 1, ' ': 2, '&': 3, '.': 4, '@': 5, 'a': 6, 'c': 7, 'b': 8, 'e': 9, 'd': 10, 'g': 11, 'f': 12, 'i': 13, 'h': 14, 'k': 15, 'j': 16, 'm': 17, 'l': 18, 'o': 19, 'n': 20, 'q': 21, 'p': 22, 's': 23, 'r': 24, 'u': 25, 't': 26, 'w': 27, 'v': 28, 'y': 29, 'x': 30, 'z': 31}
{0: '$', 1: "'", 2: ' ', 3: '&', 4: '.', 5: '@', 6: 'a', 7: 'c', 8: 'b', 9: 'e', 10: 'd', 11: 'g', 12: 'f', 13: 'i', 14: 'h', 15: 'k', 16: 'j', 17: 'm', 18: 'l', 19: 'o', 20: 'n', 21: 'q', 22: 'p', 23: 's', 24: 'r', 25: 'u', 26: 't', 27: 'w', 28: 'v', 29: 'y', 30: 'x', 31: 'z'}
$' &.@acbedgfihkjmlonqpsrutwvyxz
{0: '_', 1: "'", 2: ' ', 3: '&', 4: '.', 5: '@', 6: 'a', 7: 'c', 8: 'b', 9: 'e', 10: 'd', 11: 'g', 12: 'f', 13: 'i', 14: 'h', 15: 'k', 16: 'j', 17: 'm', 18: 'l', 19: 'o', 20: 'n', 21: 'q', 22: 'p', 23: 's', 24: 'r', 25: 'u', 26: 't', 27: 'w', 28: 'v', 29: 'y', 30: 'x', 31: 'z'}
{'_': 0, "'": 1, ' ': 2, '&': 3, '.': 4, '@': 5, 'a': 6, 'c': 7, 'b': 8, 'e': 9, 'd': 10, 'g': 11, 'f': 12, 'i': 13, 'h': 14, 'k': 15, 'j': 16, 'm': 17, 'l': 18, 'o': 19, 'n': 20, 'q': 21, 'p': 22, 's': 23, 'r': 24, 'u': 25, 't': 26, 'w': 27, 'v': 28, 'y': 29, 'x': 30, 'z': 31}
{0: '_', 1: "'", 2: ' ', 3: '&', 4: '.', 5: '@', 6: 'a', 7: 'c', 8: 'b', 9: 'e', 10: 'd', 11: 'g', 12: 'f', 13: 'i', 14: 'h', 15: 'k', 16: 'j', 17: 'm', 18: 'l', 19: 'o', 20: 'n', 21: 'q', 22: 'p', 23: 's', 24: 'r', 25: 'u', 26: 't', 27: 'w', 28: 'v', 29: 'y', 30: 'x', 31: 'z'}
_' &.@acbedgfihkjmlonqpsrutwvyxz
Traceback (most recent call last):
  File "/data/student/g2340024/Fingerspelling-PoseNet/train_with_lm.py", line 109, in <module>
    for i, (poses, labels) in enumerate(traindataloader):
  File "/home1/y2023/g2340024/.conda/envs/finger/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 708, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home1/y2023/g2340024/.conda/envs/finger/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1480, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/y2023/g2340024/.conda/envs/finger/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1505, in _process_data
    data.reraise()
  File "/home1/y2023/g2340024/.conda/envs/finger/lib/python3.11/site-packages/torch/_utils.py", line 733, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home1/y2023/g2340024/.conda/envs/finger/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home1/y2023/g2340024/.conda/envs/finger/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/y2023/g2340024/.conda/envs/finger/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/data/student/g2340024/Fingerspelling-PoseNet/data_loader.py", line 363, in __getitem__
    hand_pose = self.readHandPose(file_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/student/g2340024/Fingerspelling-PoseNet/data_loader.py", line 323, in readHandPose
    return right_joints[:,:,:2] if (df['C']== 'r').iloc[0] else left_joints[:,:,:2]
                                                                ~~~~~~~~~~~^^^^^^^^
IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed
`

**Comment by atonyo11** [comment]
Hi @wjhuang0113,

I tried to run train_with_lm.py, but I encountered the error below. Did you experience anything similar?

`
device cuda
{0: '$', 1: "'", 2: ' ', 3: '&', 4: '.', 5: '@', 6: 'a', 7: 'c', 8: 'b', 9: 'e', 10: 'd', 11: 'g', 12: 'f', 13: 'i', 14: 'h', 15: 'k', 16: 'j', 17: 'm', 18: 'l', 19: 'o', 20: 'n', 21: 'q', 22: 'p', 23: 's', 24: 'r', 25: 'u', 26: 't', 27: 'w', 28: 'v', 29: 'y', 30: 'x', 31: 'z'}
{'$': 0, "'": 1, ' ': 2, '&': 3, '.': 4, '@': 5, 'a': 6, 'c': 7, 'b': 8, 'e': 9, 'd': 10, 'g': 11, 'f': 12, 'i': 13, 'h': 14, 'k': 15, 'j': 16, 'm': 17, 'l': 18, 'o': 19, 'n': 20, 'q': 21, 'p': 22, 's': 23, 'r': 24, 'u': 25, 't': 26, 'w': 27, 'v': 28, 'y': 29, 'x': 30, 'z': 31}
{0: '$', 1: "'", 2: ' ', 3: '&', 4: '.', 5: '@', 6: 'a', 7: 'c', 8: 'b', 9: 'e', 10: 'd', 11: 'g', 12: 'f', 13: 'i', 14: 'h', 15: 'k', 16: 'j', 17: 'm', 18: 'l', 19: 'o', 20: 'n', 21: 'q', 22: 'p', 23: 's', 24: 'r', 25: 'u', 26: 't', 27: 'w', 28: 'v', 29: 'y', 30: 'x', 31: 'z'}
$' &.@acbedgfihkjmlonqpsrutwvyxz
{0: '_', 1: "'", 2: ' ', 3: '&', 4: '.', 5: '@', 6: 'a', 7: 'c', 8: 'b', 9: 'e', 10: 'd', 11: 'g', 12: 'f', 13: 'i', 14: 'h', 15: 'k', 16: 'j', 17: 'm', 18: 'l', 19: 'o', 20: 'n', 21: 'q', 22: 'p', 23: 's', 24: 'r', 25: 'u', 26: 't', 27: 'w', 28: 'v', 29: 'y', 30: 'x', 31: 'z'}
{'_': 0, "'": 1, ' ': 2, '&': 3, '.': 4, '@': 5, 'a': 6, 'c': 7, 'b': 8, 'e': 9, 'd': 10, 'g': 11, 'f': 12, 'i': 13, 'h': 14, 'k': 15, 'j': 16, 'm': 17, 'l': 18, 'o': 19, 'n': 20, 'q': 21, 'p': 22, 's': 23, 'r': 24, 'u': 25, 't': 26, 'w': 27, 'v': 28, 'y': 29, 'x': 30, 'z': 31}
{0: '_', 1: "'", 2: ' ', 3: '&', 4: '.', 5: '@', 6: 'a', 7: 'c', 8: 'b', 9: 'e', 10: 'd', 11: 'g', 12: 'f', 13: 'i', 14: 'h', 15: 'k', 16: 'j', 17: 'm', 18: 'l', 19: 'o', 20: 'n', 21: 'q', 22: 'p', 23: 's', 24: 'r', 25: 'u', 26: 't', 27: 'w', 28: 'v', 29: 'y', 30: 'x', 31: 'z'}
_' &.@acbedgfihkjmlonqpsrutwvyxz
Traceback (most recent call last):
  File "/data/student/g2340024/Fingerspelling-PoseNet/train_with_lm.py", line 109, in <module>
    for i, (poses, labels) in enumerate(traindataloader):
  File "/home1/y2023/g2340024/.conda/envs/finger/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 708, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home1/y2023/g2340024/.conda/envs/finger/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1480, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/y2023/g2340024/.conda/envs/finger/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1505, in _process_data
    data.reraise()
  File "/home1/y2023/g2340024/.conda/envs/finger/lib/python3.11/site-packages/torch/_utils.py", line 733, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home1/y2023/g2340024/.conda/envs/finger/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home1/y2023/g2340024/.conda/envs/finger/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/y2023/g2340024/.conda/envs/finger/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/data/student/g2340024/Fingerspelling-PoseNet/data_loader.py", line 363, in __getitem__
    hand_pose = self.readHandPose(file_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/student/g2340024/Fingerspelling-PoseNet/data_loader.py", line 323, in readHandPose
    return right_joints[:,:,:2] if (df['C']== 'r').iloc[0] else left_joints[:,:,:2]
           ~~~~~~~~~~~~^^^^^^^^
IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

`
